# Generated by Django 4.0.2 on 2022-06-01 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='capable_mentors',
            field=models.ManyToManyField(blank=True, null=True, related_name='capabilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='required_roles',
            field=models.ManyToManyField(related_name='modules', to='event.Role'),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_name', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='event_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_roles', to='event.eventmodule'),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_roles', to='event.role'),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_modules', to='event.event'),
        ),
        migrations.AddField(
            model_name='eventmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_modules', to='event.module'),
        ),
    ]
