# Generated by Django 4.0.2 on 2022-05-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_event_name_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.SlugField(max_length=64),
        ),
    ]
