# Generated by Django 4.0.2 on 2022-05-27 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_image_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodulerole',
            name='calendar_invites',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='invoice_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='mentoring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='onboarding',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='received_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='send_contract',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventmodulerole',
            name='sign_up',
            field=models.BooleanField(default=False),
        ),
    ]
