# Generated by Django 4.0.2 on 2022-05-19 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_languages_customuser_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='Languages',
            new_name='languages',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Location',
            new_name='location',
        ),
    ]
