# Generated by Django 4.0.2 on 2022-05-19 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_languages_customuser_languages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up', models.BooleanField(default=False)),
                ('confirmation', models.BooleanField(default=False)),
                ('send_contract', models.DateTimeField(blank=True, null=True)),
                ('received_contract', models.BooleanField(default=False)),
                ('calendar_invites', models.BooleanField(default=False)),
                ('onboarding', models.BooleanField(default=False)),
                ('mentoring', models.BooleanField(default=False)),
                ('invoice_sent', models.BooleanField(default=False)),
                ('paid', models.BooleanField(default=False)),
                ('mentor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
