# Generated by Django 4.0.2 on 2022-05-27 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_mentorprocess_send_contract'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MentorProcess',
        ),
    ]
